services:
  app:
    build: .
    container_name: exotic_vendor_app
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: vendor_portal_test
      DB_USERNAME: vendor_user
      DB_PASSWORD: eXotic@123

  db:
    image: mysql:8.4
    container_name: exotic_vendor_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: vendor_portal_test
      MYSQL_USER: vendor_user
      MYSQL_PASSWORD: eXotic@123
      MYSQL_ROOT_PASSWORD: eXotic@123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: exotic_vendor_pma
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 256M
    depends_on:
      - db

volumes:
  db_data:
